### PR TITLE
LRQA-72463 | master

### PR DESCRIPTION
**Pull request by Hijky**
Test for ci:test:sf

### CODE REVIEW

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:sf

**Comment by Hijky** [comment]
ci:test:sf

**Comment by ling-alan-huang** [comment]
Hi @Hijky I resolved conflicting files and resent: https://github.com/Hijky/liferay-portal/pull/9

**Comment by ling-alan-huang** [comment]
ci:close

**Pull request closed without merging**
